---

- name: update system
  become: true
  hosts: all
  tasks:
    - apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
        autoclean: yes

- name: Install daily tools
  become: true
  hosts: all
  tasks:
    - apt:
        name:
            - curl
            - nginx
            - docker.io
        state: present

- name: setup webserver
  become: true
  hosts: webserver
  tasks:
    - ansible.builtin.user:
      user:
        name: "deploy"
        append: yes
        groups: docker

    - name: Set authorized key took from file 
      ansible.posix.authorized_key:
        user: deploy
        state: present
        key: "{{ lookup('file', './serdarkey') }}"

  
